{{- if eq .Values.gohelm.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default (include "app.name" .) .Values.gohelm.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gohelm.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.appName" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.appName" . }}
{{- if or (.Values.prometheus.create) (.Values.gohelm.pod.annotations) }}
      annotations:
{{- if .Values.prometheus.create }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
{{- end }}
{{- if .Values.gohelm.pod.annotations }}
{{ toYaml .Values.gohelm.pod.annotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.gohelm.volumes }}
      volumes:
{{ toYaml .Values.gohelm.volumes | indent 6 }}
{{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      hostNetwork: {{ .Values.gohelm.hostNetwork }}
      containers:

      - image: "{{ .Values.gohelm.image.repository }}"
        name: {{ include "app.name" . }}
        imagePullPolicy: "{{ .Values.gohelm.image.pullPolicy }}"
        ports:
        - name: http
          containerPort: {{ .Values.gohelm.port }}
{{ if .Values.gohelm.customPorts }}
{{ toYaml .Values.gohelm.customPorts | indent 8 }}
{{ end }}
{{- if .Values.prometheus.create }}
        - name: prometheus
          containerPort: {{ .Values.prometheus.port }}
{{- end }}
        resources:
{{ toYaml .Values.gohelm.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- if .Values.gohelm.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.gohelm.volumeMounts | indent 8 }}
{{- end }}
        env:
        - name: APP_PORT
          value: "{{ .Values.gohelm.port }}"
        - name: PROMETHEUS_PORT
          value: "{{ .Values.prometheus.port }}"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{- end }}
